# Generated by Django 3.1.5 on 2022-05-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220522_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='브랜드'),
        ),
    ]
