# Generated by Django 3.1.5 on 2022-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='할인가격'),
        ),
    ]
