# Generated by Django 3.1.5 on 2022-07-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image_detail',
            field=models.ImageField(blank=True, upload_to='products_detail/%Y/%m/%d'),
        ),
    ]
