# Generated by Django 3.1.5 on 2022-07-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='address_country',
            field=models.CharField(max_length=250, null=True, verbose_name='도시와 나라'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_house',
            field=models.CharField(max_length=250, null=True, verbose_name='주거지'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='구매자'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='우편번호'),
        ),
    ]
