# Generated by Django 3.1.5 on 2022-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220708_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_country',
            field=models.CharField(max_length=250, null=True, verbose_name='도시 주소'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_house',
            field=models.CharField(max_length=250, null=True, verbose_name='주거지 주소'),
        ),
        migrations.DeleteModel(
            name='OrderTransaction',
        ),
    ]
