# Generated by Django 3.1.5 on 2022-07-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220711_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_house',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='order',
            name='tel',
            field=models.CharField(max_length=30, null=True, verbose_name='휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='이메일'),
        ),
    ]
